version: '3.9'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:7

  celery_worker:
    build: .
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
