version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dtc_clean
      POSTGRES_PASSWORD: 12345pass
      POSTGRES_DB: dtc_clean_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"


volumes:
  postgres_data:
